# Numpy
En este notebook, se desarrollarán una serie de tareas utilizando la librería Numpy (Numerical Python). Se proponen y documentan posibles formas de resolver los ejercicios, pero las mismas no son únicas. Siempre es una buena idea verificar la [Documentación Oficial de Numpy](https://numpy.org/devdocs/user/index.html), donde es posible encontrar todo tipo de información referida a esta librería.

In [1]:
# Importamos Numpy con su abreviación "np"
import numpy as np

In [9]:
# Podemos crear arrays de una dimensión con la función np.array()
arrayUnidim = np.array([1, 2, 3, 4, 5])

# O un array de dos dimensiones (bidimensional)
arrayBidim = np.array([[1, 2, 3], [4, 5, 6]])

# O un array de tres dimensiones (tridimensional)
arrayTridim = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

Para cada uno de estos arrays, podemos obtener sus propiedades, tales como su "forma", número de dimensiones, tipos de datos y tamaño.

In [4]:
# Atributos del array unidimensional (forma, número de dimensiones, tipos de datos, tamaño, y tipo)
arrayUnidim.shape, arrayUnidim.ndim, arrayUnidim.dtype, arrayUnidim.size, type(arrayUnidim)

((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [5]:
# Atributos del array bidimensional
arrayBidim.shape, arrayBidim.ndim, arrayBidim.dtype, arrayBidim.size, type(arrayBidim)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [10]:
# Atributos del array tridimensional
arrayTridim.shape, arrayTridim.ndim, arrayTridim.dtype, arrayTridim.size, type(arrayTridim)

((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [12]:
# Importamos pandas como pd, y creamos un DataFrame a partir del array bidimensional
import pandas as pd
datos = pd. DataFrame(arrayBidim)
datos

0  1  2
0  1  2  3
1  4  5  6

In [13]:
# Creamos un array de tamaño 4x3, formado únicamente por unos (1)
unos = np.ones((4, 3))
unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
# Creamos un array de tamaño 2x4x3, formado únicamente por ceros (0)
ceros = np.zeros((2, 4, 3))
ceros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
# Creamos un array de números en el rango de 0 a 100, con un paso de 5
array_1 = np.arange(0, 100+1, 5)
array_1

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [21]:
# Creamos un array de números aleatorios enteros comprendidos en entre 0 y 10, de tamaño (2, 5)
array_2 = np.random.randint(0, 10, (2, 5))
array_2

array([[3, 6, 8, 1, 9],
       [2, 5, 1, 2, 9]])

In [22]:
# Creamos un array de números aleatorios decimales comprendidos en entre 0 y 1, de tamaño (3, 5)
array_3 = np.random.random((3, 5))
array_3

array([[0.37597857, 0.51791728, 0.58369551, 0.2652491 , 0.86000315],
       [0.89032069, 0.78013821, 0.95693678, 0.2380455 , 0.92361564],
       [0.94978671, 0.77342084, 0.85997874, 0.25909338, 0.60022162]])

In [24]:
# Establecemos la "semilla" de números aleatorios en 27
np.random.seed(27)
# Creamos un array de números aleatorios enteros comprendidos en entre 0 y 10, de tamaño (3, 5)
array_4 = np.random.randint(0, 10, (3, 5))
array_4

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2],
       [1, 1, 4, 6, 3]])

¿Qué ocurre al correr la última celda nuevamente, a diferencia de las anteriores?

In [25]:
# Encontramos los valores únicos del array_4
np.unique(array_4)

array([0, 1, 2, 3, 4, 5, 6, 8, 9])

In [28]:
# Extraemos el elemento de índice 1 del array_4
array_4[1]

array([5, 8, 9, 1, 2])

In [29]:
# Extraemos las primeras dos filas del array_4
array_4[:2]

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2]])

In [30]:
# Extraemos los dos primeros datos de las primeras dos filas del array_4
array_4[:2, :2]

array([[3, 8],
       [5, 8]])

In [41]:
# Creamos dos arrays de tamaño 3x4: uno relleno de números aleatorios entre 0 y 10, y otro relleno de unos
array_5= np.random.randint(0, 10, (3, 4))
array_6 = np.ones((3, 4))
array_5

array([[6, 3, 6, 1],
       [4, 1, 8, 1],
       [2, 4, 2, 0]])

In [43]:
# invocamos el array_5
array_5

array([[6, 3, 6, 1],
       [4, 1, 8, 1],
       [2, 4, 2, 0]])

In [40]:
# invocamos el array_6
array_6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [44]:
# Sumamos los dos arrays
array_5 + array_6

array([[7., 4., 7., 2.],
       [5., 2., 9., 2.],
       [3., 5., 3., 1.]])

In [45]:
# Creamos ahora un array de tamaño (4,3) lleno de unos
array_7 = np.ones((4, 3))

In [46]:
# Intentaremos sumar los arrays 6 y 7
array_6 + array_7

ValueError: ignored

¿A qué se debe el error anterior? ¿Qué deberíamos tener en cuenta para que no suceda?

In [47]:
# Entonces crearemos otro array de tamaño (4,3) lleno de unos
array_8 = np.ones((4, 3))

In [48]:
# Restamos el array_8 al array_7
array_8 - array_7

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
# Creamos otros dos arrays de tamaño 3x3 con números aleatorios del 1 al 5
array_9 = np.random.randint(1, 5, (3, 3))
array_10 = np.random.randint(1, 5, (3, 3))

In [50]:
# invocamos el array_9
array_9

array([[1, 4, 2],
       [4, 2, 3],
       [1, 4, 4]])

In [51]:
# invocamos el array_10
array_10

array([[1, 2, 4],
       [1, 1, 3],
       [1, 3, 1]])

In [52]:
# Multiplicamos los últimos dos arrays entre sí
array_10 * array_9

array([[ 1,  8,  8],
       [ 4,  2,  9],
       [ 1, 12,  4]])

In [53]:
# Elevamos el array_9 al cuadrado
array_9 ** 2

array([[ 1, 16,  4],
       [16,  4,  9],
       [ 1, 16, 16]])

In [54]:
# Buscamos la raíz cuadrada del array_10
np.sqrt(array_10)

array([[1.        , 1.41421356, 2.        ],
       [1.        , 1.        , 1.73205081],
       [1.        , 1.73205081, 1.        ]])

In [57]:
from numpy.lib.function_base import median
# Hallamos el promedio de los valores del array_9
array_9.mean()

2.7777777777777777

In [59]:
# Hallamos el valor máximo de los valores del array_9
array_9.max()

4

In [60]:
# Hallamos el valor mínimo de los valores del array_9
array_9.min()

1

In [61]:
# Cambiamos la forma del array_9 por una de 9x1, y lo almacenamos como array_11
array_11 = array_9.reshape((9, 1))

In [62]:
# invocamos el array_11
array_11

array([[1],
       [4],
       [2],
       [4],
       [2],
       [3],
       [1],
       [4],
       [4]])

In [63]:
# Transponemos el array_11
array_11.T

array([[1, 4, 2, 4, 2, 3, 1, 4, 4]])

In [64]:
# Comparamos el array_9 y el array_10, para saber cuáles elementos del array_9 son mayores a los del array_10
array_9 > array_10

array([[False,  True, False],
       [ True,  True, False],
       [False,  True,  True]])

¿Qué tipos de datos forman parte del array de resultados?

In [65]:
# Veamos sus nuevos tipos de datos
array_10.dtype

dtype('int64')

In [66]:
# Alguno de los elementos del array_9 es igual su equivalente del array_10?
array_9 == array_10

array([[ True, False, False],
       [False, False,  True],
       [ True, False, False]])

In [67]:
# Comparamos nuevamente ambos arrays, en esta ocasión con >=
array_9 >= array_10

array([[ True,  True, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [68]:
# Buscamos los elementos del array_9 que son mayores a 2
array_9 > 2

array([[False,  True, False],
       [ True, False,  True],
       [False,  True,  True]])

In [69]:
# Ordenamos de menor a mayor los elementos dentro del array_9
np.sort(array_9)

array([[1, 2, 4],
       [2, 3, 4],
       [1, 4, 4]])